AWSTemplateFormatVersion: 2010-09-09

Parameters:

  AMIID:
    Type: String
    Description: AMI ID of the AMI
  KeyPairName:
    Type: String
    Description: AMI ID of the AMI

Resources:

  # Create S3 backup IAM role and policy
  PanintelligenceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Panintelligence-IAM-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        # The managed IAM policy AmazonSSMManagedInstanceCore grants access to Session Manager
        #- !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  SecretPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: panintelligence-secret
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'secretsmanager:GetResourcePolicy'
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:DescribeSecret'
              - 'secretsmanager:ListSecretVersionIds'
            Resource:
              - !ImportValue MyRDSSecret
          - Effect: Allow
            Action:
              - 'secretsmanager:ListSecrets'
            Resource:
              - '*'
      Roles:
        - !Ref PanintelligenceRole

  MyInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref PanintelligenceRole

  PanintelligenceLaunchTemplate:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AMIID
      InstanceType: t3.medium
      IamInstanceProfile: !Ref MyInstanceProfile
      SecurityGroups:
          - Fn::ImportValue: PrivateSecurityGroup
          - Fn::ImportValue: SecurityGroupEc2Instance
          - Fn::ImportValue: EFSMountTarget
      KeyName: !Ref KeyPairName
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash -x
              mkdir -p /mnt/efs/
              echo "${EfsFileSystemId}.efs.${AWS::Region}.amazonaws.com:/ /mnt/efs nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0" >> /etc/fstab
              mount -a -t nfs4
              rm -r /var/panintelligence/images
              rm -r /var/panintelligence/themes
              rm -r /var/panintelligence/excel
              rm -r /var/panintelligence/keys
              rm -r /var/panintelligence/logs
              mkdir -p /mnt/efs/var/panintelligence/images /mnt/efs/var/panintelligence/themes /mnt/efs/var/panintelligence/excel /mnt/efs/var/panintelligence/logs /mnt/efs/var/panintelligence/keys
              ln -s /mnt/efs/var/panintelligence/images /var/panintelligence/images
              ln -s /mnt/efs/var/panintelligence/themes /var/panintelligence/themes
              ln -s /mnt/efs/var/panintelligence/logs /var/panintelligence/logs
              ln -s /mnt/efs/var/panintelligence/excel /var/panintelligence/excel
              ln -s /mnt/efs/var/panintelligence/keys /var/panintelligence/keys
              echo "PI_DB_HOST=${DBHost}" | tee -a /var/panintelligence/dashboard.env /var/panintelligence/scheduler.env
              echo "PI_DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ${SecretArn} --query SecretString --output text --region ${Region} | jq -r .password)" | tee -a /var/panintelligence/dashboard.env /var/panintelligence/scheduler.env
              echo "PI_DB_PORT=${DBPort}" | tee -a /var/panintelligence/dashboard.env /var/panintelligence/scheduler.env
              echo "PI_DB_SCHEMA_NAME='dashboard'" | tee -a /var/panintelligence/dashboard.env /var/panintelligence/scheduler.env
              echo "PI_DB_USERNAME=$(aws secretsmanager get-secret-value --secret-id ${SecretArn} --query SecretString --output text --region ${Region} | jq -r .username)" | tee -a /var/panintelligence/dashboard.env /var/panintelligence/scheduler.env
              echo "PI_EXTERNAL_DB='true'" >> /var/panintelligence/dashboard.env
              chmod +rwx /var/panintelligence/images
              chmod +rwx /var/panintelligence/themes
              chmod +rwx /var/panintelligence/logs
              chmod +rwx /var/panintelligence/excel
              chmod +rwx /var/panintelligence/keys
              chown -h pi-user:pi-group /var/panintelligence/images
              chown -h pi-user:pi-group /var/panintelligence/themes
              chown -h pi-user:pi-group /var/panintelligence/logs
              chown -h pi-user:pi-group /var/panintelligence/excel
              chown -h pi-user:pi-group /var/panintelligence/keys
              reboot
            - EfsFileSystemId: !ImportValue FileSystem
              DBHost: !ImportValue MyDBEndPoint
              SecretArn: !ImportValue MyRDSSecret
              DBPort: 3306
              DashboardLicenceKey: !Ref DashboardLicenceKey
              Region: !Ref "AWS::Region"



  PanintelligenceAutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue: PrivateSubnetA
      LaunchConfigurationName: !Ref PanintelligenceLaunchTemplate
      MinSize: '1'
      MaxSize: '5'
      DesiredCapacity: '1'
      HealthCheckGracePeriod: 300
      MaxInstanceLifetime: 2592000
      TargetGroupARNs:
        - Fn::ImportValue: TargetGroup
      Tags:
        - Key: Name
          Value: Panintelligence
          PropagateAtLaunch: "true"

  myScaleOutPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PanintelligenceAutoscalingGroup
      ScalingAdjustment: '1'

  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: '70'
      AlarmDescription: Alarm if CPU too high or metric disappears indicating instance
        is down
      Period: '60'
      AlarmActions:
      - !Ref myScaleOutPolicy
      Namespace: AWS/EC2
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: PanintelligenceAutoscalingGroup
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUUtilization

  myScaleInPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PanintelligenceAutoscalingGroup
      ScalingAdjustment: '-1'

  CPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '2'
      Statistic: Average
      Threshold: '10'
      AlarmDescription: Alarm if CPU too low or metric disappears indicating instance
        is down
      Period: '60'
      AlarmActions:
      - !Ref myScaleInPolicy
      Namespace: AWS/EC2
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: PanintelligenceAutoscalingGroup
      ComparisonOperator: LessThanThreshold
      MetricName: CPUUtilization